name:                ghc-mod-nvim
version:             0.1.0.0
license:             Apache-2.0
license-file:        LICENSE

dependencies:
- base >= 4.7 && < 5

executables:
  ghc-mod-nvim:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - nvim-hs
    - ghc-mod-nvim

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
    - nvim-hs >= 1.0.0.0
    - nvim-hs-contrib >= 1.0.0.0
    - mtl
    - stm
    - lens
    - extra
    - parsec
    - process
    - deepseq
    - unliftio
    - filepath
    - exceptions
    - bytestring
    - basic-prelude
